sudo: required 
services:
  - docker  

#berofe_install:
before_install:
  - docker build -t jojoshuajosh/docker-react -f Dockerfile.dev .
  
script:
    - docker run -e CI=true jojoshuajosh/docker-react npm run test -- --coverage --watchAll=false