sudo: required 
services:
  - docker  

#berofe_install:
before_install:
  #- docker build -t jojoshuajosh/docker-react -f Dockerfile.dev .
  - docker build -t test/docker-react -f Dockerfile.dev .
  
script:
    - docker run -e test/docker-react npm run test -- --coverage