sudo: required 
services:
  - docker  

#berofe_install:
before_install:
  - docker build -t jojoshuajosh/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true jojoshuajosh/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-780853863518"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


      


