sudo: required 
services:
  - docker  

berofe_install:
  - docker build -t jojoshuajosh/docker-react -f Dockerfile.dev .
  
script:
    - docker run jojoshuajosh/docker-react npm run test -- --coverage